version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: gradle
    directory: "/lambdas/death-enrichment"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: gradle
    directory: "/lambdas/death-minimisation"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: gradle
    directory: "/lambdas/death-validation"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: gradle
    directory: "/lib"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: bundler
    directory: "/techdocs"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
