version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: docker
    directory: "/prometheus"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: docker
    directory: "/grafana"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: bundler
    directory: "/techdocs"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: npm
    directory: /terraform/modules/gro_ingestion_service/lambdas
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
