version: "3"
services:
  gdx-data-share-poc:
    build: .
    networks:
      - gds
      - hmpo
    container_name: gdx-data-share-poc
    depends_on:
      - datashare-db
      - localstack
      - oauth2
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      - SQS_LOCALSTACK_URL=http://localstack:4566
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev,localstack
      - API_BASE_URL_ISSUER_URI=http://oauth2:8080/issuer1
      - API_BASE_URL_OAUTH=http://oauth2:8080/issuer1
      - API_BASE_URL_LEV=http://lev-api:8080
      - API_BASE_URL_DATA_RECEIVER=http://gdx-data-share-poc:8080
      - DB_URI=postgresql://datashare-db:5432/datashare?sslmode=disable
    links:
      - localstack:egress.localstack
      - localstack:dev-ingress-archive-gdx-data-share-poc.localstack
      - localstack:dev-ingress-gdx-data-share-poc.localstack

  localstack:
    image: localstack/localstack:0.14.0
    networks:
      - gds
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    ports:
      - "4566:4566"
      - "8999:8080"
    environment:
      - SERVICES=sns,sqs
      - DEBUG=${DEBUG- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_EXECUTION_ENV=True
      - HOSTNAME=${LOCALSTACK_DOCKER_NAME-localstack}
      - HOSTNAME_EXTERNAL=${LOCALSTACK_DOCKER_NAME-localstack}
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  datashare-db:
    image: postgres:13.7
    networks:
      - gds
    container_name: datashare-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=datashare
      - POSTGRES_USER=datashare
      - POSTGRES_DB=datashare

  lev-api:
    image: quay.io/governmentdigitalservices/lev-api:latest
    container_name: lev-api
    networks:
      - hmpo
    environment:
      - LISTEN_HOST=0.0.0.0
      - LISTEN_PORT=8080
      - POSTGRES_USER=lev
      - POSTGRES_PASSWORD=lev
      - POSTGRES_HOST=lev-db
      - POSTGRES_ADMIN_USER=root
      - POSTGRES_ADMIN_PASSWORD=root
      - POSTGRES_SSL=FALSE
    ports:
      - "8099:8080"
  lev-db:
    build:
      context: lev-data/
    networks:
      - hmpo
    container_name: lev-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=lev
      - APP_USER=lev
      - APP_PASSWORD=lev
    ports:
      - "5433:5432"

  oauth2:
    image: ghcr.io/navikt/mock-oauth2-server:0.5.6
    container_name: oauth2
    networks:
      - gds
    ports:
      - "9090:8080"
    environment:
      - JSON_CONFIG_PATH=/tmp/config.json
      - SERVER_PORT=8080
    volumes:
      - ${PWD}/oauth2-data:/tmp/

networks:
  gds:
  hmpo:
