version = 0.1

[default]

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "eu-west-2"

[dev-oskwil.deploy.parameters]
stack_name = "oskwil-lev"
s3_prefix = "oskwil-lev"
parameter_overrides = "Environment=\"dev\" VpcStackName=\"vpc\" Developer=\"oskwil\""

[dev-hanleo.deploy.parameters]
stack_name = "hanleo-lev"
s3_prefix = "hanleo-lev"
parameter_overrides = "Environment=\"dev\" VpcStackName=\"vpc\" Developer=\"hanleo\""

[dev-mwillis.deploy.parameters]
stack_name = "mwillis-lev"
s3_prefix = "mwillis-lev"
parameter_overrides = "Environment=\"dev\" VpcStackName=\"vpc\" Developer=\"mwillis\""
