AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  This creates the necessary serverless components for the Life Events Platform.


Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
        POWERTOOLS_TRACER_CAPTURE_RESPONSE: false
        POWERTOOLS_TRACER_CAPTURE_ERROR: false
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue

Parameters:
  Environment:
    Type: String
    Description: The name of the environment to deploy to
  CodeSigningConfigArn:
    Type: String
    Description: The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Default: "none"
  PermissionsBoundary:
    Type: String
    Description: The ARN of the permissions boundary to apply when creating IAM roles
    Default: "none"

Conditions:
  UseCodeSigning:
    Fn::Not:
      - Fn::Equals:
          - !Ref CodeSigningConfigArn
          - "none"
  UsePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "none"

Resources:
  MasterKmsKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
          - Effect: Allow
            Principal:
              Service: !Sub "logs.${AWS::Region}.amazonaws.com"
            Action:
              - "kms:Encrypt*"
              - "kms:Decrypt*"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:Describe*"
            Resource: "*"
            Condition:
              ArnLike:
                "kms:EncryptionContext:aws:logs:arn": !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
          - Effect: Allow
            Principal:
              Service: "sns.amazonaws.com"
            Action:
              - "kms:Decrypt"
              - "kms:GenerateDataKey*"
            Resource: "*"

  DeathValidationDlq:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: !Ref MasterKmsKey

  DeathEnrichmentQueue:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: !Ref MasterKmsKey
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeathEnrichmentDlq.Arn
        maxReceiveCount: 5

  DeathEnrichmentDlq:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: !Ref MasterKmsKey

  DeathDistributionTopic:
    Type: AWS::SNS::Topic
    Properties:
      KmsMasterKeyId: !Ref MasterKmsKey

  DeathSnsToSqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "Allow SNS publish to SQS"
            Effect: Allow
            Principal:
              Service: "sns.amazonaws.com"
            Resource: "*"
            Action: SQS:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref DeathDistributionTopic
      Queues:
        - !GetAtt DeathMinimisationQueue.QueueUrl

  DeathDistributionDlq:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: !Ref MasterKmsKey

  DeathDistributionTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      Endpoint: !GetAtt DeathMinimisationQueue.Arn
      TopicArn: !GetAtt DeathDistributionTopic.TopicArn
      RawMessageDelivery: true
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeathDistributionDlq.Arn

  DeathMinimisationQueue:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: !Ref MasterKmsKey
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeathMinimisationDlq.Arn
        maxReceiveCount: 5

  DeathMinimisationDlq:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: !Ref MasterKmsKey

  DeathDeliveryQueue:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: !Ref MasterKmsKey

  DeathValidationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "death-validation-${Environment}"
      CodeUri: lambdas/death-validation
      Handler: uk.gov.di.data.lep.GroDeathValidation::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      KmsKeyArn: !GetAtt MasterKmsKey.Arn
      Tracing: Active
      Environment:
        Variables:
          TARGET_QUEUE: !GetAtt DeathEnrichmentQueue.QueueUrl
      AutoPublishAlias: DeathValidationFunction
      VpcConfig:
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
      Events:
        DeathApiEvent:
          Type: Api
          Properties:
            Method: POST
            Path: /events/deathNotification/
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt DeathValidationDlq.Arn
      Policies:
        - Statement:
            - Sid: KmsMasterKeyAccess
              Effect: Allow
              Action:
                - 'kms:Decrypt'
                - 'kms:GenerateDataKey'
              Resource:
                - !GetAtt MasterKmsKey.Arn
        - SQSSendMessagePolicy:
            QueueName: !GetAtt DeathEnrichmentQueue.QueueName

  DeathEnrichmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "death-enrichment-${Environment}"
      CodeUri: lambdas/death-enrichment
      Handler: uk.gov.di.data.lep.GroDeathEnrichment::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      KmsKeyArn: !GetAtt MasterKmsKey.Arn
      Tracing: Active
      Environment:
        Variables:
          TARGET_TOPIC: !GetAtt DeathDistributionTopic.TopicArn
      AutoPublishAlias: DeathEnrichmentFunction
      VpcConfig:
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
      Events:
        DeathValidatedEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt DeathEnrichmentQueue.Arn
            BatchSize: 1
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt DeathEnrichmentDlq.Arn
      Policies:
        - Statement:
            - Sid: KmsMasterKeyAccess
              Effect: Allow
              Action:
                - 'kms:Decrypt'
                - 'kms:GenerateDataKey'
              Resource:
                - !GetAtt MasterKmsKey.Arn
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt DeathDistributionTopic.TopicName

  DeathMinimisationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "death-minimisation-${Environment}"
      CodeUri: lambdas/death-minimisation
      Handler: uk.gov.di.data.lep.GroDeathNotificationMinimisation::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      KmsKeyArn: !GetAtt MasterKmsKey.Arn
      Tracing: Active
      Environment:
        Variables:
          ENRICHMENT_FIELDS: FORENAMES, SURNAME
          TARGET_QUEUE: !GetAtt DeathDeliveryQueue.QueueUrl
      AutoPublishAlias: DeathMinimisationFunction
      VpcConfig:
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
      Events:
        DeathEnrichedEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt DeathMinimisationQueue.Arn
            BatchSize: 1
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt DeathMinimisationDlq.Arn
      Policies:
        - Statement:
            - Sid: KmsMasterKeyAccess
              Effect: Allow
              Action:
                - 'kms:Decrypt'
                - 'kms:GenerateDataKey'
              Resource:
                - !GetAtt MasterKmsKey.Arn
        - SQSSendMessagePolicy:
            QueueName: !GetAtt DeathDeliveryQueue.QueueName

  SQSEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Join
        - ''
        - - com.amazonaws.
          - !Ref 'AWS::Region'
          - .sqs
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      VpcId: !Ref Vpc
      VpcEndpointType: Interface
      SecurityGroupIds:
        - !Ref SQSSecurityGroup
      PrivateDnsEnabled: true

  SQSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SQS Security Group
      VpcId: !Ref Vpc
      SecurityGroupIngress:
        - CidrIp: !GetAtt Vpc.CidrBlock
          Description: Allow inbound traffic from VPC cidr to port 443
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443

  SNSEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Join
        - ''
        - - com.amazonaws.
          - !Ref 'AWS::Region'
          - .sns
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      VpcId: !Ref Vpc
      VpcEndpointType: Interface
      SecurityGroupIds:
        - !Ref SNSSecurityGroup
      PrivateDnsEnabled: true

  SNSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SNS Security Group
      VpcId: !Ref Vpc
      SecurityGroupIngress:
        - CidrIp: !GetAtt Vpc.CidrBlock
          Description: Allow inbound traffic from VPC cidr to port 443
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Lambda Security Group
      VpcId: !Ref Vpc
      SecurityGroupEgress:
        - DestinationSecurityGroupId: !GetAtt SQSSecurityGroup.GroupId
          Description: Allow outbound traffic to SQS VPC endpoint
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
        - DestinationSecurityGroupId: !GetAtt SNSSecurityGroup.GroupId
          Description: Allow outbound traffic to SNS VPC endpoint
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443

  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${Environment} Private Subnet (AZ1)

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${Environment} Private Subnet (AZ2)

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
