hmpps.sqs:
  reactiveApi: true
  provider: localstack
  queues:
    dataprocessor:
      queueName: dataprocessor-queue
      dlqName: dataprocessor-dlq
    audit:
      queueName: ${random.uuid}
    adaptor:
      queueName: legacy-adaptor-event-queue
      dlqName: legacy-adaptor-event-dlq
      subscribeTopicId: event
      subscribeFilter: '{"eventType":[ "LIFE_EVENT", "DEATH_NOTIFICATION" ] }'
    odg:
      queueName: ogd-event-queue
      dlqName: ogd-event-dlq
      subscribeTopicId: event
      subscribeFilter: '{"eventType":[ "DEATH_NOTIFICATION" ] }'
  topics:
    event:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}
