server:
  shutdown: immediate

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

spring:
  devtools:
    add-properties: true

  flyway:
    url: jdbc:postgresql://localhost:5432/datashare?sslmode=prefer
    user: datashare
    password: datashare

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/datashare?sslmode=prefer
    username: datashare
    password: datashare
    properties:
      sslMode: DISABLE
      sslRootCert:

api:
  base:
    url:
      issuer-uri: https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_qUBXvU9L8
      oauth: https://gdx-data-share.auth.eu-west-2.amazoncognito.com
      lev: http://localhost:8099
      hmrc: https://a0519c3b-e75b-41aa-b79d-7bb41871ec62.mock.pstmn.io
      data-receiver: http://localhost:8080