sqs:
  provider: localstack
  queues:
    dataprocessor:
      queueName: dataprocessor-queue
      dlqName: dataprocessor-dlq
    audit:
      queueName: ${random.uuid}

  topics:
    event:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}
