server:
  shutdown: immediate

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

metrics:
  cloudwatch:
    namespace: "local-gdx"

spring:
  devtools:
    add-properties: true

  flyway:
    url: jdbc:postgresql://localhost:5432/datashare?sslmode=prefer
    user: datashare
    password: datashare
    locations: classpath:db/migration, classpath:db/devonly

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/datashare?sslmode=prefer
    username: datashare
    password: datashare
    properties:
      sslMode: DISABLE
      sslRootCert:
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: INFO # for parameters

api:
  base:
    url:
      issuer-uri: http://localhost:9090/issuer1
      oauth: http://localhost:9090/issuer1
      lev: http://localhost:8099
      data-receiver: http://localhost:8080
      event-data-retrieval: http://localhost:8080
    s3:
      ingress: ingress
      ingress-archive: ingress-archive

legacy-inbound:
  api:
    client:
      id: clientId
      secret: clientSecret

legacy-outbound:
  api:
    client:
      id: clientId
      secret: clientSecret