sqs:
  provider: localstack
  queues:
    dataprocessor:
      queueName: dataprocessor-queue
      dlqName: dataprocessor-dlq
    prisoner-event:
      queueName: prisoner-event-queue
      dlqName: prisoner-event-dlq
