sqs:
  provider: localstack
  queues:
    supplierevent:
      queueName: supplier-event-queue
      dlqName: supplier-event-dlq
    acquirerevent:
      queueName: acquirer-event-queue
      dlqName: acquirer-event-dlq
    prisonerevent:
      queueName: prisoner-event-queue
      dlqName: prisoner-event-dlq
