server:
  shutdown: immediate

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health, metrics'

metrics:
  cloudwatch:
    namespace: "local-gdx"

spring:
  datasource:
    url: jdbc:aws-wrapper:postgresql://localhost:5432/datashare?sslmode=disable
    username: datashare
    password: datashare

  devtools:
    add-properties: true

  flyway:
    locations: classpath:db/migration, classpath:db/devonly

api:
  base:
    consume-outbound-by-queue: false
    url:
      issuer-uri: http://localhost:9090/issuer1
      oauth: http://localhost:9090/issuer1
      lev: http://localhost:8099
