environment: dev

server:
  shutdown: immediate

management:
  endpoint:
    health:
      cache:
        time-to-live: 0
      show-details: always
      show-components: always
    info:
      cache:
        time-to-live: 0
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health, metrics, prometheus'

spring:
  datasource:
    url: jdbc:aws-wrapper:postgresql://localhost:5432/datashare?sslmode=disable&wrapperPlugins=%22%22
    username: datashare
    password: datashare

  devtools:
    add-properties: true

  flyway:
    locations: classpath:db/migration, classpath:db/devonly

prometheus:
  user:
    name: prometheus
    password: prometheus
    role: ACTUATOR

api:
  base:
    prisoner-event:
      enabled: true
    prisoner-search:
      api:
        client:
          id: prisoner-search-client
          secret: prisoner-search-secret
    lev:
      api:
        client:
          name: gdx-data-share
          user: gdx-data-share-user
    url:
      issuer-uri: http://localhost:9090/issuer1
      oauth: http://localhost:9090/issuer1
      lev: http://localhost:8099
      prisoner-search: http://localhost:8082
      hmpps-auth: http://localhost:9090/issuer1

xray-tracing:
  enabled: false

cognito:
  enabled: false

task-role-arn: arn:aws:iam::776473272850:role/dev-task-role
