global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gdx'
    metrics_path: /prometheus
    honor_labels: true
    static_configs:
      - targets: ['host.docker.internal:8080']
    basic_auth:
      username: prometheus
      password: prometheus
