version: "3"
services:
  grafana:
    build: .
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - AWS_SDK_LOAD_CONFIG=true
      - GF_AUTH_SIGV4_AUTH_ENABLED=true
    volumes:
      - grafana_storage:/var/lib/grafana grafana/grafana-enterprise
    healthcheck:
      test: wget --tries=1 --spider http://localhost:3000/health

volumes:
  grafana_storage: {}
