AWSTemplateFormatVersion: "2010-09-09"

Description: Initialises an account for DI Life Events Platform, this should be run before the secure pipeline stack
Parameters:
  Environment:
    Description: The name of the environment to deploy to
    Type: String
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production
  SlackChannelId:
    Description: The ID of the slack channel to send notifications to
    Type: String
    Default: "none"

Conditions:
  IsProduction: !Equals [ !Ref Environment, production]
  EnableSlackNotifications:
    Fn::Not:
      - Fn::Equals:
          - !Ref SlackChannelId
          - "none"

Resources:
  LambdaAuditHook:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://template-storage-templatebucket-1upzyw6v9cs42.s3.amazonaws.com/lambda-audit-hook/template.yaml

  CheckovHook:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://template-storage-templatebucket-1upzyw6v9cs42.s3.amazonaws.com/checkov-hook/template.yaml

  InfraAuditHook:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://template-storage-templatebucket-1upzyw6v9cs42.s3.amazonaws.com/infrastructure-audit-hook/template.yaml

  GrafanaMetrics:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://template-storage-templatebucket-1upzyw6v9cs42.s3.amazonaws.com/grafana-metrics/template.yaml
      Parameters:
        GrafanaEnvironment: !If
          - IsProduction
          - "prod"
          - "non-prod"

  APIGatewayLogging:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://template-storage-templatebucket-1upzyw6v9cs42.s3.amazonaws.com/api-gateway-logs/template.yaml

  SlackNotifications:
    Type: AWS::CloudFormation::Stack
    Condition: EnableSlackNotifications
    Properties:
      TemplateURL: https://template-storage-templatebucket-1upzyw6v9cs42.s3.amazonaws.com/build-notifications/template.yaml
      Parameters:
        SlackChannelId: !Ref SlackChannelId

  Vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://template-storage-templatebucket-1upzyw6v9cs42.s3.amazonaws.com/vpc/template.yaml
      Parameters:
        SNSApiEnabled: "Yes"
        SQSApiEnabled: "Yes"
