name: Application - Main

permissions:
  id-token: write
  contents: read
  checks: write

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - "terraform/**"
      - "!terraform/modules/data-share-service/ecs.tf"

concurrency:
  group: application-pipeline-${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  test:
    uses: ./.github/workflows/shared/test.yml

  build-and-push-image:
    name: Build and push docker image
    needs: test
    uses: ./.github/workflows/main/build-and-push.yml

  deploy-dev:
    name: Deploy dev environment
    needs: build-and-push-image
    uses: ./.github/workflows/main/codedeploy.yml
    with:
      environment: dev
      image: ${{ needs.build-and-push-image.outputs.image }}

  deploy-demo:
    name: Deploy demo environment
    needs: build-and-push-image
    uses: ./.github/workflows/main/codedeploy.yml
    with:
      environment: demo
      image: ${{ needs.build-and-push-image.outputs.image }}

