name: Application

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "terraform/**"
  pull_request:
    paths-ignore:
      - "terraform/**"

concurrency:
  group: application-pipeline-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build-and-push-image:
    name: Build ${{ (github.event_name == 'push' && github.ref_name == 'main') && 'and push' || '' }} docker image
    needs: test
    uses: ./.github/workflows/build-and-push.yml
    with:
      push: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}