name: Application - Pull request

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "terraform/**"
      - "!terraform/modules/data-share-service/ecs.tf"

concurrency:
  group: application-pipeline-${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  test:
    uses: ./.github/workflows/test.yml

  openapi-lint:
    uses: ./.github/workflows/openapi-lint.yml

