name: Application - Main

permissions:
  id-token: write
  contents: read
  checks: write

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - "terraform/**"
      - "!terraform/modules/data-share-service/ecs.tf"

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build-and-push-image:
    name: Build and push docker image
    needs: test
    uses: ./.github/workflows/build-and-push.yml

  deploy-dev:
    name: Deploy dev environment
    needs: build-and-push-image
    uses: ./.github/workflows/codedeploy.yml
    with:
      environment: dev
      image: ${{ needs.build-and-push-image.outputs.image }}
      registry: ${{ needs.build-and-push-image.outputs.registry }}

  deploy-demo:
    name: Deploy demo environment
    needs: build-and-push-image
    uses: ./.github/workflows/codedeploy.yml
    with:
      environment: demo
      image: ${{ needs.build-and-push-image.outputs.image }}
      registry: ${{ needs.build-and-push-image.outputs.registry }}

