name: Application - Pull request

permissions:
  id-token: write
  contents: read
  checks: write
  pull-requests: write

on:
  workflow_dispatch:
  pull_request:
  merge_group:

concurrency:
  group: application-pipeline-${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets:
      SAM_APP_VALIDATE_ROLE_ARN: ${{ secrets.SAM_APP_VALIDATE_ROLE_ARN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
