name: Application - Pull request

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/**"
      - "!terraform/modules/data-share-service/ecs.tf"

jobs:
  test:
    uses: ./.github/workflows/autopass/test-autopass.yml

  openapi-lint:
    uses: ./.github/workflows/autopass/openapi-lint-autopass.yml
