name: Build and push

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean
        default: false
        description: Whether to push the image, or otherwise just build
    secrets:
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
    outputs:
      image:
        value: ${{ jobs.build-image.outputs.image }}

jobs:
  build-image:
    name: Build Docker image ${{ inputs.push && 'and push to ECR' || '' }}
    environment: dev
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.push-image.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and tag image
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: false
          tags: ${{ github.sha }}

      - name: Configure AWS credentials
        if: inputs.push
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          mask-aws-account-id: false

      - name: Login to Amazon ECR
        if: inputs.push
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push base image to Amazon ECR
        if: inputs.push
        id: push-image
        env:
          IMAGE: ${{ steps.login-ecr.outputs.registry }}/gdx-data-share-poc:${{ github.sha }
        run: |
          docker tag ${{ github.sha } $IMAGE
          docker push $IMAGE
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

  tag-environments:
    name: Tag docker image for ${{ matrix.env }} environment
    needs: build-image
    if: inputs.push
    strategy:
      matrix:
        env: [dev, demo]
    environment: ${{ matrix.env }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          mask-aws-account-id: false

      - name: Add tag for ${{ matrix.env }} environment
        uses: abronin/ecr-retag-action@v1
        with:
          repository: gdx-data-share-poc
          tag: ${{ github.sha }}
          new-tags: ${{ matrix.env }}
