name: Fix gradle lockfile for dependabot

on:
  pull_request:
    types: [ labeled ]

jobs:
  update-gradle-lock:
    if: ${{ github.event.label.name == 'dependabot-gradle' }}
    name: Fix gradle lockfile for dependabot
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 20

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Update lockfile
        run: ./gradlew dependencies --write-locks

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "GPC-NONE: Automatically update gradle.lockfile"
          file_pattern: 'gradle.lockfile'
