version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
  - package-ecosystem: terraform
    directory: "/terraform"
    schedule:
      interval: daily
    commit-message:
      prefix: "GPC-NONE"
