name: Run E2E tests

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      COGNITO_CLIENT_SECRET:
        required: true

env:
  ENVIRONMENT: ${{ inputs.environment }}
  API_URL: ${{ vars.API_URL }}
  COGNITO_TOKEN_URL: ${{ vars.COGNITO_TOKEN_URL }}
  COGNITO_CLIENT_ID: ${{ vars.COGNITO_CLIENT_ID }}
  COGNITO_CLIENT_SECRET: ${{ secrets.COGNITO_CLIENT_SECRET }}

jobs:
  e2e-test:
    name: Run E2E tests
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.8.0

      - name: Execute Gradle build
        run: ./gradlew clean platform:e2eTest

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test results
          path: "**/build/test-results/e2eTest/TEST-*.xml"
          reporter: java-junit
          only-summary: true

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: junit-test-results
          path: '**/build/test-results/e2eTest/TEST-*.xml'
          retention-days: 1
