name: Infrastructure - Pull request

permissions:
  id-token: write
  contents: write

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/**"
  merge_group:
    paths:
      - "terraform/**"
      - ".github/workflows/**"

jobs:
  tf-fmt:
    name: Validate Terraform formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.2

      - name: Check formatting of all Terraform files
        run: terraform fmt -check -diff -recursive

  validate-terraform:
    strategy:
      matrix:
        env: [dev, demo, shared]
      fail-fast: false
    name: Validate ${{ matrix.env }} Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/${{ matrix.env }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up mutex
        uses: ben-z/gh-action-mutex@v1.0-alpha-7
        with:
          branch: ${{ matrix.env }}-mutex-terraform-locking

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::776473272850:role/github-oidc-pull-request
          role-session-name: validate-terraform
          aws-region: eu-west-2
          mask-aws-account-id: false

      - name: Set up Terraform
        # Exposes stdout, stderr and exitcode as outputs for any steps that run terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.2

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -var-file=../tfvars/non-prod/${{ matrix.env }}.tfvars

