name: Infrastructure

on:
  push:
    branches:
      - "main"
    paths:
      - "terraform/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/**"

concurrency:
  group: infrastructure-pipeline
  cancel-in-progress: false

jobs:
  tf-fmt:
    name: Validate Terraform formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.2

      - name: Check formatting of all Terraform files
        run: terraform fmt -check -diff -recursive

  validate-infrastructure:
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        env: [dev, demo]
      fail-fast: false
    name: Validate ${{ matrix.env }} Terraform
    needs: tf-fmt
    uses: ./.github/workflows/terraform-shared.yml
    with:
      working-directory: terraform/${{ matrix.env }}
      apply: false
      environment: ${{ matrix.env }}
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

  deploy-infrastructure:
    if: github.event_name == 'push' && github.ref_name == 'main'
    strategy:
      matrix:
        env: [dev, demo]
      fail-fast: false
    name: Deploy to ${{ matrix.env }} environment
    needs: tf-fmt
    uses: ./.github/workflows/terraform-shared.yml
    with:
      working-directory: terraform/${{ matrix.env }}
      apply: true
      environment: ${{ matrix.env }}
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}