name: Infrastructure - Pull request

on:
  pull_request:
    paths-ignore:
      - "terraform/**"
      - ".github/workflows/**"
  merge_group:
    paths-ignore:
      - "terraform/**"
      - ".github/workflows/**"

jobs:
  tf-fmt:
    name: Validate Terraform formatting
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'

  validate-terraform:
    strategy:
      matrix:
        include:
          - env: dev
            account: non-prod
          - env: demo
            account: non-prod
          - env: shared
            account: non-prod
          - env: prod
            account: prod
      fail-fast: false
    name: Validate ${{ matrix.account }} ${{ matrix.env }} Terraform
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
