name: Kotlin automatically fix linting

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "src/**"

jobs:
  tf-fmt:
    name: Validate and fix formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew clean formatKotlin

      - name: Create pull request if required
        uses: peter-evans/create-pull-request@v4
        with:
          title: "housekeeping: Automatically format Kotlin files"
          commit-message: "housekeeping: Automatically format Kotlin files"
