name: Kotlin automatically fix linting

on:
  pull_request:
    paths:
      - "src/**"

jobs:
  kotlin-fmt:
    name: Validate and fix formatting
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 20

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew clean formatKotlin

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "GPC-NONE: Automatically reformat Kotlin files"
          file_pattern: '*.kt'

