name: Run Trivy for lambdas

on:
  workflow_dispatch:
  pull_request:
  merge_group:

jobs:
  validate-gds:
    strategy:
      matrix:
        include:
          - module: lambdas
            scanref: ./lambdas
            trivyignore: lambdas/.trivyignore
          - module: lib
            scanref: ./lib
            trivyignore: lib/.trivyignore
      fail-fast: false
    name: Validate gds
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy gradle for gds lambdas
        run: |
          cp -r gradle ${{ matrix.module }}/gradle
          cp gradlew ${{ matrix.module }}/gradlew
          cp gradlew.bat ${{ matrix.module }}/gradlew.bat

      - name: Run Trivy vulnerability scanner on lambdas
        uses: aquasecurity/trivy-action@0.12.0
        with:
          scan-type: fs
          scan-ref: ${{ matrix.scanref }}
          trivyignores: ${{ matrix.trivyignore }}
          exit-code: 1
