name: Automatically lint files

on:
  workflow_dispatch:
  pull_request:

jobs:
  fmt:
    name: Format files
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0

      - name: Update gradle lockfiles
        run: ./gradlew resolveAndLockAll --write-locks

      - name: Fix formatting of java files
        run: ./gradlew spotlessApply

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.COMMIT_BOT_GPG_KEY }}
          passphrase: ${{ secrets.COMMIT_BOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "GPC-NONE: Automatically lint files"
          file_pattern: '**/gradle.lockfile *.java'
          disable_globbing: true
          commit_user_name: Life Events Platform[bot]
          commit_user_email: di-life-events-platform@digital.cabinet-office.gov.uk
          commit_author: Life Events Platform[bot] <di-life-events-platform@digital.cabinet-office.gov.uk>

