name: OpenAPI lint

on:
  workflow_call:

jobs:
  openapi-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.5.1

      - name: Spin up localstack and db
        uses: yu-ichiro/spin-up-docker-compose-action@v1
        with:
          file: docker-compose-local.yml

      - name: Generate API docs
        run: ./gradlew -Pdocs platform:generateOpenApiDocs

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Lint API docs
        run: npx @stoplight/spectral-cli lint build/openapi.json
