name: OpenAPI lint

on:
  workflow_call:

jobs:
  openapi-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Spin up localstack and db
        uses: yu-ichiro/spin-up-docker-compose-action@v1
        with:
          file: docker-compose-local.yml

      - name: Generate API docs
        run: ./gradlew -Pdocs generateOpenApiDocs

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Lint API docs
        run: npx @stoplight/spectral-cli lint build/openapi.json -o junit-lint-results.xml -f junit

      - name: Upload Lint Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: junit-lint-results
          path: '**/junit-lint-results.xml'
          retention-days: 1
