name: Run scheduled Trivy scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
  pull_request:

jobs:
  validate-images:
    strategy:
      matrix:
        include:
          - image: gdx
            context: ./
            trivyignore: .trivyignore
          - image: prometheus
            context: ./prometheus
            trivyignore: prometheus/.trivyignore
          - image: grafana
            context: ./grafana
            trivyignore: grafana/.trivyignore
      fail-fast: false
    name: Validate ${{ matrix.image }} image
    runs-on: ubuntu-latest
    outputs:
      gdx-outcome: ${{ steps.output.outputs.gdx-outcome || '' }}
      gdx-table: ${{ steps.output.outputs.gdx-table || '' }}
      prometheus-outcome: ${{ steps.output.outputs.prometheus-outcome || '' }}
      prometheus-table: ${{ steps.output.outputs.gdx-table || '' }}
      grafana-outcome: ${{ steps.output.outputs.grafana-outcome || '' }}
      grafana-table: ${{ steps.output.outputs.gdx-table || '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and tag image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          push: false
          tags: ${{ github.ref_name }}:${{ matrix.image }}
          load: true
          cache-to: type=gha
          cache-from: type=gha

      - id: trivy
        name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.10.0
        continue-on-error: true
        with:
          image-ref: ${{ github.ref_name }}:${{ matrix.image }}
          trivyignores: ${{ matrix.trivyignore }}
          exit-code: 1
          format: table
          output: ${{ matrix.image }}.table

      - id: output
        name: Setup output
        run: |
          echo "${{ matrix.image }}-outcome=${{ steps.trivy.outcome }}" >> $GITHUB_OUTPUT
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "${{ matrix.image }}-table<<$EOF" >> $GITHUB_OUTPUT
          cat ${{ matrix.image }}.table >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

  validate-infra:
    name: Validate infra code
    runs-on: ubuntu-latest
    outputs:
      terraform-outcome: ${{ steps.output.outputs.gdx-outcome }}
      terraform-table: ${{ steps.output.outputs.gdx-table }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: trivy
        name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.10.0
        continue-on-error: true
        with:
          scan-type: config
          trivyignores: .trivyignore.docker
          skip-dirs: lev-data/
          exit-code: 1
          format: table
          output: terraform.table

      - id: output
        name: Setup output
        run: |
          echo "terraform-outcome=${{ steps.trivy.outcome }}" >> $GITHUB_OUTPUT
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "terraform-table<<$EOF" >> $GITHUB_OUTPUT
          cat terraform.table >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

  notify-slack:
    name: Notify Slack
    needs: [validate-images, validate-infra]
    runs-on: ubuntu-latest
    steps:
      - id: payload
        name: Construct payload
        run: |
          payload='{
            "text": "Trivy dependency scan failed\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Trivy dependency scan failed\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                },
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Scan*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Outcome*"
                  },
                  {
                    "type": "plain_text",
                    "text": "GDX"
                  },
                  {
                    "type": "plain_text",
                    "text": "${{ needs.validate-images.outputs.gdx-outcome }}"
                  },
                  {
                    "type": "plain_text",
                    "text": "Prometheus"
                  },
                  {
                    "type": "plain_text",
                    "text": "${{ needs.validate-images.outputs.prometheus-outcome }}"
                  },
                  {
                    "type": "plain_text",
                    "text": "Grafana"
                  },
                  {
                    "type": "plain_text",
                    "text": "${{ needs.validate-images.outputs.grafana-outcome }}"
                  },
                  {
                    "type": "plain_text",
                    "text": "terraform"
                  },
                  {
                    "type": "plain_text",
                    "text": "${{ needs.validate-infra.outputs.terraform-outcome }}"
                  }
                ]
              },
              {
                "type": "divider"
              }
            ]
          }'

          if [ -n "${{ needs.validate-images.outputs.gdx-table }}" ]
          then
            payload=$(jq '.blocks += [{
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "GDX table\n${{ needs.validate-images.outputs.gdx-table }}"
              }
            }]' <<< $payload)
          fi

          if [ -n "${{ needs.validate-images.outputs.prometheus-table }}" ]
          then
            payload=$(jq '.blocks += [{
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "Prometheus table\n${{ needs.validate-images.outputs.prometheus-table }}"
              }
            }]' <<< $payload)
          fi

          if [ -n "${{ needs.validate-images.outputs.grafana-table }}" ]
          then
            payload=$(jq '.blocks += [{
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "Grafana table\n${{ needs.validate-images.outputs.grafana-table }}"
              }
            }]' <<< $payload)
          fi

          if [ -n "${{ needs.validate-infra.outputs.terraform-table }}" ]
          then
            payload=$(jq '.blocks += [{
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "terraform table\n${{ needs.validate-infra.outputs.terraform-table }}"
              }
            }]' <<< $payload)
          fi

          echo "payload=$payload" >> $GITHUB_OUTPUT

      - name: Send failure message to Slack
        if: needs.validate-images.outputs.gdx-outcome != 'success' || needs.validate-images.outputs.prometheus-outcome != 'success' || needs.validate-images.outputs.grafana-outcome != 'success' || needs.validate-infra.outputs.terraform-outcome != 'success'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: ${{ steps.payload.outputs.payload }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
