name: Terraform plan and apply

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
        default: "."
        description: Directory to run Terraform commands from
      apply:
        required: false
        type: boolean
        default: false
        description: Whether to apply config, or otherwise just plan
      environment:
        required: true
        type: string
        description: Specify the environment to plan/apply

jobs:
  plan:
    name: Terraform plan ${{ inputs.apply && 'and apply' || '' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::776473272850:role/${{ inputs.environment }}-github-oidc-deploy
          role-session-name: codedeploy
          aws-region: eu-west-2
          mask-aws-account-id: false

      - name: Set up Terraform
        # Exposes stdout, stderr and exitcode as outputs for any steps that run terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.2

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Plan
        id: plan
        # Terraform's "detailed-exitcode" codes are: 0 for "no changes", 1 for errors, 2 for "valid changes"
        # Output a plan even though we don't use it here - we need the printed output to be the same as in the apply job below
        # We don't save the plan as an artefact as it's sensitive and this repo is public
        run: terraform plan -no-color -input=false -detailed-exitcode -out=plan.tfplan
        continue-on-error: true

      - name: Fail job if plan failed
        run: if [ ${{ steps.plan.outputs.exitcode }} -eq 1 ]; then exit 1; else exit 0; fi

      - name: Terraform Apply
        if: inputs.apply && steps.plan.outputs.exitcode == 2
        run: terraform apply -auto-approve -input=false plan.tfplan
