name: Terraform plan and apply

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
        default: "."
        description: Directory to run Terraform commands from
      apply:
        required: false
        type: boolean
        default: false
        description: Whether to apply config, or otherwise just plan
      environment:
        required: true
        type: string
        description: Specify the environment to plan/apply
    secrets:
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true

jobs:
  plan:
    name: Terraform plan ${{ inputs.apply && 'and apply' || '' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    env:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        # Exposes stdout, stderr and exitcode as outputs for any steps that run terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.2

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Plan
        id: plan
        # Terraform's "detailed-exitcode" codes are: 0 for "no changes", 1 for errors, 2 for "valid changes"
        # Output a plan even though we don't use it here - we need the printed output to be the same as in the apply job below
        # We don't save the plan as an artefact as it's sensitive and this repo is public
        run: terraform plan -no-color -input=false -detailed-exitcode -out=plan.tfplan
        continue-on-error: true

      - name: Terraform Apply
        if: inputs.apply && steps.plan.outputs.plan_exitcode == 2
        run: terraform apply -auto-approve -input=false plan.tfplan