name: "Deployment"

on:
  push:
    branches:
      - "main"
    paths:
      - "terraform/**"
      - ".github/workflows/**"

jobs:
  tf-fmt:
    name: Validate Terraform formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.2

      - name: Check formatting of all Terraform files
        run: terraform fmt -check -diff -recursive
  deploy-poc:
    name: Deploy to "poc" environment
    needs: tf-fmt
    uses: ./.github/workflows/terraform-shared.yml
    with:
      working-directory: terraform/poc
      apply: true
      environment: poc
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
