name: Run lambda tests

on:
  workflow_dispatch:
  pull_request:
  merge_group:

jobs:
  test:
    name: Run lambda tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Test lambdas
        working-directory: ./terraform/modules/gro_ingestion_service/lambdas
        run: |
          npm ci
          npm run test
