name: Run tests

on:
  workflow_call:

jobs:
  test:
    permissions:
      contents: read
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: platform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Execute Gradle build
        run: ./gradlew clean test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test results
          path: "**/build/test-results/test/TEST-*.xml"
          reporter: java-junit
          only-summary: true

      - name: Report test coverage
        uses: madrapps/jacoco-report@7ce0d588f6d00dd4a7b63a597383332e0c5c72d0
        if: ${{ github.event_name == 'pull_request' }}
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: junit-test-results
          path: '**/build/test-results/test/TEST-*.xml'
          retention-days: 1
