name: Run tests

on:
  workflow_call:
    secrets:
      SAM_APP_VALIDATE_ROLE_ARN:
        required: true

jobs:
  test:
    permissions:
      contents: read
      checks: write
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.6.1

      - name: Execute Gradle build
        run: ./gradlew clean test

      - name: Report test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test results
          path: ${{ github.workspace }}/**/build/test-results/test/TEST-*.xml
          reporter: java-junit
          only-summary: true

      - name: Report test coverage
        uses: madrapps/jacoco-report@7ce0d588f6d00dd4a7b63a597383332e0c5c72d0
        if: ${{ github.event_name == 'pull_request' }}
        with:
          paths: ${{ github.workspace }}/platform/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up SAM cli
        uses: aws-actions/setup-sam@v2
        if: always()
        with:
          use-installer: true

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@v2
        if: always()
        with:
          role-to-assume: ${{ secrets.SAM_APP_VALIDATE_ROLE_ARN }}
          role-session-name: validate-sam
          aws-region: eu-west-2

      - name: SAM validate
        if: always()
        run: sam validate --lint
