name: Run tests

on:
  workflow_call:
    secrets:
      SAM_APP_VALIDATE_ROLE_ARN:
        required: true

jobs:
  test:
    permissions:
      contents: read
      checks: write
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.6.0

      - name: Execute Gradle build
        run: ./gradlew clean test

      - name: Publish test results
        uses: mikepenz/action-junit-report@959aefb7f095e717eb407fe917238d61ca323ff3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Report test coverage
        uses: madrapps/jacoco-report@7ce0d588f6d00dd4a7b63a597383332e0c5c72d0
        if: ${{ github.event_name == 'pull_request' }}
        with:
          paths: ${{ github.workspace }}/platform/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up SAM cli
        uses: aws-actions/setup-sam@v2
        if: always()

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@v1-node16
        if: always()
        with:
          role-to-assume: ${{ secrets.SAM_APP_VALIDATE_ROLE_ARN }}
          aws-region: eu-west-2

      - name: SAM validate
        if: always()
        run: sam validate --lint
