name: TFSec

on:
  push:
    branches:
      - "main"
    paths:
      - "terraform/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/**"

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: terraform/
