name: Run Trivy

on:
  workflow_call:

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and tag image
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: false
          tags: ${{ github.ref_name }}:latest
          load: true
          cache-to: type=gha
          cache-from: type=gha

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/gdx-data-share-poc:${{ github.sha }}
          trivyignores: .trivyignore
          trivy-config: trivy.yaml
