name: Run Trivy

on:
  workflow_dispatch:
  pull_request:
  merge_group:

jobs:
  validate-images:
    strategy:
      matrix:
        include:
          - image: gdx
            context: platform
            trivyignore: platform/.trivyignore
          - image: prometheus
            context: prometheus
            trivyignore: prometheus/.trivyignore
          - image: grafana
            context: grafana
            trivyignore: grafana/.trivyignore
      fail-fast: false
    name: Validate ${{ matrix.image }} image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Copy gradle for gdx
        if: matrix.image == 'gdx'
        run: |
          cp -r gradle platform/gradle
          cp gradlew platform/gradlew
          cp gradlew.bat platform/gradlew.bat

      - name: Build and tag image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          push: false
          tags: ${{ github.ref_name }}:${{ matrix.image }}
          load: true
          cache-to: type=gha
          cache-from: type=gha

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.11.2
        with:
          image-ref: ${{ github.ref_name }}:${{ matrix.image }}
          trivyignores: ${{ matrix.trivyignore }}
          exit-code: 1

  validate-infra:
    name: Validate infra code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.11.2
        with:
          scan-type: config
          trivyignores: .trivyignore.docker
          exit-code: 1
          skip-dirs: lev-data/
          skip-files: template.yaml
