name: Trivy Infrastructure scan

on:
  push:
    branches:
      - "main"
    paths:
      - "terraform/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/**"
  merge_group:
    paths:
      - "terraform/**"
      - ".github/workflows/**"

jobs:
  trivy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          exit-code: '1'
          trivyignores: .trivyignore
          trivy-config: trivy.yaml
