name: Update Grafana

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "grafana/**"

jobs:
  build-grafana-image:
    name: Build Docker image and push to ECR
    environment: dev
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: grafana
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and tag image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{ github.ref_name }}:latest
          load: true
          cache-to: type=gha
          cache-from: type=gha

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ github.ref_name }}:latest
          exit-code: 1
          trivyignores: .trivyignore

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::776473272850:role/dev-github-oidc-deploy
          role-session-name: push-grafana-image
          aws-region: eu-west-2
          mask-aws-account-id: false

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push base image to Amazon ECR
        id: push-image
        env:
          IMAGE: ${{ steps.login-ecr.outputs.registry }}/grafana
        run: |
          docker tag ${{ github.ref_name }}:latest $IMAGE:${{ github.sha }}
          docker tag ${{ github.ref_name }}:latest $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest

      - name: Force redeployment of Grafana instance
        run: |
          aws ecs update-service --force-new-deployment --service grafana --cluster grafana
