name: Validate Prometheus

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "prometheus/**"
  merge_group:
    paths:
      - "prometheus/**"

jobs:
  validate-prometheus:
    name: Validate Prometheus
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: prometheus
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and tag image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{ github.ref_name }}:latest
          load: true
          cache-to: type=gha
          cache-from: type=gha

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ github.ref_name }}:latest
          exit-code: 1
          trivyignores: prometheus/.trivyignore
